#!/bin/sh

SSHFS_OPTIONS="reconnect ServerAliveInterval=15 ServerAliveCountMax=3
	       follow_symlinks"

fusermount -uz $HOME/aws 2>&1 > /dev/null
sshfs -o $(echo ${SSHFS_OPTIONS} | tr ' ' ',') server3.cerebras.net: $HOME/aws
