#!/bin/sh

vnc_display=:15
vnc_host=server3.cerebras.net
vnc_user=jeff
ssh_options="-o ServerAliveInterval=15 -o ServerAliveCountMax=10"

vnc_tcp_port=59${vnc_display:(-2)}

if ! nc -z -w1 localhost ${vnc_tcp_port}; then
    echo -n "Starting ssh tunnel to ${vnc_host}..."
    ssh -L ${vnc_tcp_port}:localhost:${vnc_tcp_port} -N -f \
	-l ${vnc_user} ${vnc_host}
    ssh_exitcode=$?
    if [ ${ssh_exitcode} -eq 0 ]; then
	echo "Success"
    else
	echo "Failure"
	exit ${ssh_exitcode}
    fi
fi

exec vncviewer -PasswordFile ${HOME}/.vnc/passwd ${vnc_display}
